name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: isabela-mnz
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

      - name: Commit e enviar ao repositório
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Atualizando snake animation'
          git push
